context("Diagnostic Plotting functions")

test_that("AnalyzeAndPlotretval", {

  #The retvalx was generated by:
  #clean.chlist <- MultipleSetupAndPosterior( input.catalog = input.catalog[1:96 , 1:15],
  #                                           seedNumber          = 44,
  #                                           K.guess             = 5,
  #                                           multi.types         = FALSE,
  #                                           verbose             = TRUE,
  #                                           post.burnin         = 1000,
  #                                           post.n              = 50,
  #                                           post.space          = 50,
  #                                           post.cpiter         = 3,
  #                                           post.verbosity      = 0,
  #                                           CPU.cores           = 2,
  #                                           num.child.process   = 2)



  #retvalx <- CombinePosteriorChains(clean.chlist = clean.chlist,
  #                                  input.catalog = input.catalog[1:96 , 1:15],
  #                                  multi.types = FALSE,
  #                                  verbose = TRUE)

  reg <- new.env()
  load("RunhdpInternal.testdata/test.AnalyzeAndPlotretval.Rdata",
       envir = reg)


  AnalyzeAndPlotretval(retval = reg$retvalx,
                       out.dir = "./test_AnalyzeAndPlotretval_out_dir")
})

